baseURL: https://tutukuaipao.github.io/dcx_resume/
languageCode: zh-cn
defaultContentLanguage: zh
title: "王志的个人简历"
theme: toha

# Use Hugo modules to add theme
module:
  imports:
    - path: github.com/hugo-toha/toha/v4
      mounts:
        - source: layouts
          target: layouts
        - source: static
          target: static
        - source: assets
          target: assets
        - source: i18n
          target: i18n
        - source: archetypes
          target: archetypes
  mounts:
    - source: static/files
      target: static/files
    - source: ./node_modules/flag-icons/flags
      target: static/flags
    - source: ./node_modules/@fontsource/mulish/files
      target: static/files
    - source: ./node_modules/katex/dist/fonts
      target: static/fonts

# Manage languages
languages:
  zh:
    languageCode: zh-cn
    languageName: 中文
    weight: 1
    title: "王志的个人简历"
    description: "王志的个人简历网站"

# Control TOC depth
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

# At least HTML and JSON are required for the main HTML content and
# client-side JavaScript search
outputs:
  home:
    - HTML
    - RSS
    - JSON

# Enable global emoji support
enableEmoji: true

# Site parameters
params:
  # Background image of the landing page
  background: /images/site/background.png

  # Provide logos for your site. The inverted logo will be used in the initial
  # transparent navbar and the main logo will be used in the non-transparent navbar.
  logo:
    main: /images/site/main-logo.png
    inverted: /images/site/inverted-logo.png
    favicon: /images/site/favicon.png

  # GitHub repo URL of your site
  gitRepo: https://github.com/tutukuaipao/dcx_resume
  gitBranch: master

  # Configure the number of section title visible in the top navbar
  topNavbar:
    maxVisibleSections: 5

  # Configure various features of this theme
  features:
    # Enable and configure portfolio
    portfolio:
      enable: true

    # Enable and configure blog posts
    blog:
      enable: true
      showAuthor: true

    # Enable & configure "Notes" features
    notes:
      enable: true

    # Enable comment feature
    comment:
      enable: false

    # Enable analytics
    analytics:
      enabled: false

    # specify whether you want to show Table of Contents in reading page
    toc:
      enable: true

    # Show tags under the post title
    tags:
      enable: true

  # Provide footer configuration.
  footer:
    enable: true
    navigation:
      enable: true
    contactMe:
      enable: true
    newsletter:
      enable: false

# Enable and configure "Notes" features
notes:
  enable: true

# Enable comment feature
comment:
  enable: false

# Enable analytics
analytics:
  enabled: false 