baseURL: https://tutukuaipao.github.io/dcx_resume/
languageCode: zh-cn
defaultContentLanguage: zh
title: "王志的个人简历"
theme: toha

# Use Hugo modules to add theme
module:
  imports:
    - path: github.com/hugo-toha/toha/v4
      mounts:
        - source: layouts
          target: layouts
        - source: static
          target: static
        - source: assets
          target: assets
        - source: i18n
          target: i18n
        - source: archetypes
          target: archetypes
  mounts:
    - source: assets
      target: assets
    - source: static/files
      target: static/files
    - source: ./node_modules/flag-icons/flags
      target: static/flags
    - source: ./node_modules/@fontsource/mulish/files
      target: static/files
    - source: ./node_modules/katex/dist/fonts
      target: static/fonts
    - source: ./node_modules/bootstrap/scss
      target: assets/scss/bootstrap
    - source: ./node_modules/include-media/dist
      target: assets/scss/include-media
    - source: ./node_modules/bootstrap/dist/js/bootstrap.bundle.min.js
      target: assets/js/bootstrap.bundle.min.js
    - source: ./node_modules/@fortawesome/fontawesome-free/js/all.min.js
      target: assets/js/fontawesome.min.js
    - source: ./node_modules/@popperjs/core/dist/umd/popper.min.js
      target: assets/js/popper.min.js
    - source: ./node_modules/filterizr/dist/jquery.filterizr.min.js
      target: assets/js/filterizr.min.js
    - source: ./node_modules/jquery/dist/jquery.min.js
      target: assets/js/jquery.min.js

# Manage languages
languages:
  zh:
    languageCode: zh-cn
    languageName: 中文
    weight: 1
    title: "王志的个人简历"
    description: "王志的个人简历网站"

# Control TOC depth
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

# Configure security
security:
  funcs:
    getenv:
      - ^HUGO_
      - ^CI$
  http:
    methods:
      - GET
    urls:
      - .*

# Build configuration
build:
  buildStats:
    enable: true
  cachebusters:
    - source: assets/.*\.(js|ts|jsx|tsx)$
      target: public/js/
    - source: assets/.*\.(css|sass|scss)$
      target: public/css/
  useResourceCacheWhen: fallback

# Configure SCSS processing
sass:
  transpiler: dartsass
  outputStyle: compressed
  precision: 6
  sourceMap: true
  includePaths:
    - node_modules
    - assets/scss

# Configure JavaScript processing
js:
  build:
    includePaths:
      - node_modules
      - assets/js
    minify: true
    sourceMap: true
    target: es2015
    format: iife

# Site parameters
params:
  # Background image of the landing page
  background: /images/site/background.png

  # Provide logos for your site
  logo:
    main: /images/site/main-logo.png
    inverted: /images/site/inverted-logo.png
    favicon: /images/site/favicon.png

  # GitHub repo URL of your site
  gitRepo: https://github.com/tutukuaipao/dcx_resume
  gitBranch: master

  # Configure the number of section title visible in the top navbar
  topNavbar:
    maxVisibleSections: 5

  # Configure various features of this theme
  features:
    portfolio:
      enable: true
    blog:
      enable: true
      showAuthor: true
    notes:
      enable: true
    comment:
      enable: false
    analytics:
      enabled: false
    toc:
      enable: true
    tags:
      enable: true

  # Configure footer
  footer:
    enable: true
    navigation:
      enable: true
    contactMe:
      enable: true
    newsletter:
      enable: false

# Outputs configuration
outputs:
  home:
    - HTML
    - RSS
    - JSON

# Enable global emoji support
enableEmoji: true

# Enable and configure "Notes" features
notes:
  enable: true

# Enable comment feature
comment:
  enable: false

# Enable analytics
analytics:
  enabled: false 