baseURL = 'https://tutukuaipao.github.io/dcx_resume/'
languageCode = 'zh-cn'
title = '个人简历'
theme = 'hugo-resume'

# 添加资源处理配置
[module]
  [[module.mounts]]
    source = "static"
    target = "static"

[params]
  author = "张三"
  description = "个人简历"
  mainSections = ["sections"]
  firstName = "张"
  lastName = "三"
  address = "深圳"
  phone = "188-xxxx-xxxx"
  email = "zhangsan@example.com"
  favicon = "images/favicon.ico"
  # 社交媒体链接
  profileImage = "images/profile.jpg"
  showQr = true

  # 简历部分
  showSkills = true
  showProjects = true
  showOpenSource = true
  showPublications = true
  showExperience = true
  showEducation = true
  showBlog = false
  showCV = false

[outputs]
  home = ["HTML", "JSON"]

[[params.handles]]
  name = "GitHub"
  link = "https://github.com/username"

[[params.handles]]
  name = "LinkedIn"
  link = "https://linkedin.com/in/username"

[menu]
  [[menu.main]]
    name = "首页"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "关于"
    url = "#about"
    weight = 2
  [[menu.main]]
    name = "经历"
    url = "#experience"
    weight = 3
  [[menu.main]]
    name = "技能"
    url = "#skills"
    weight = 4
  [[menu.main]]
    name = "项目"
    url = "#projects"
    weight = 5 