baseURL: https://tutukuaipao.github.io/dcx_resume/
languageCode: zh-cn
title: "王志的个人简历"
theme: toha

# Use Hugo modules to add theme
module:
  imports:
    - path: github.com/hugo-toha/toha/v4

# Manage languages
languages:
  zh:
    languageCode: zh-cn
    languageName: 中文
    weight: 1
    home: 首页
    # copyright
    copyright: © 2024 版权所有

# Control TOC depth
markup:
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

# At least HTML and JSON are required for the main HTML content and
# client-side JavaScript search
outputs:
  home:
    - HTML
    - RSS
    - JSON

# Enable global emoji support
enableEmoji: true

# Site parameters
params:
  # Background image of the landing page
  background: /images/site/background.jpg

  # Provide logos for your site. The inverted logo will be used in the initial
  # transparent navbar and the main logo will be used in the non-transparent navbar.
  logo:
    main: /images/site/main-logo.png
    inverted: /images/site/inverted-logo.png
    favicon: /images/site/favicon.png

  # GitHub repo URL of your site
  gitRepo: https://github.com/tutukuaipao/dcx_resume
  gitBranch: master

  features:
    # Enable and configure portfolio
    portfolio:
      enable: true

    # Enable and configure blog posts
    blog:
      enable: true

    # Enable & configure "Notes" features
    notes:
      enable: true

    # Enable comment feature
    comment:
      enable: false

    # Enable analytics
    analytics:
      enabled: false

# specify whether you want to show Table of Contents in reading page
enableTOC: true

# Provide newsletter configuration.
newsletter:
  enable: false 