baseURL = 'http://example.org/'
languageCode = 'zh-cn'
title = '个人简历'
theme = 'hugo-vitae'

[params]
    # 主题颜色
    color = 'dark'
    
    # 头像设置
    avatar = 'img/profile.jpg'
    
    # 个人信息
    subtitle = '个人简历'
    name = '您的姓名'
    location = '城市，省份'
    email = 'your.email@example.com'
    phone = '电话号码'
    
    # 社交媒体链接
    github = 'your-github-username'
    linkedin = 'your-linkedin-username'
    
    # 简历设置
    enableResume = true
    resumeTitle = '个人简历'

[menu]
  [[menu.main]]
    identifier = 'about'
    name = '关于我'
    url = '/about/'
    weight = 1
  
  [[menu.main]]
    identifier = 'experience'
    name = '工作经验'
    url = '/experience/'
    weight = 2
  
  [[menu.main]]
    identifier = 'education'
    name = '教育经历'
    url = '/education/'
    weight = 3

[params.google]
    analytics = "UA-XXXXXXXXX-X"
