baseURL = "http://example.org/"
title = "个人简历"
theme = "PaperMod"
languageCode = "zh-cn"
defaultContentLanguage = "zh"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[params]
    env = "production"
    description = "个人简历"
    author = "您的姓名"
    
    defaultTheme = "auto"
    ShowShareButtons = false
    ShowReadingTime = false
    displayFullLangName = true
    ShowPostNavLinks = true
    ShowBreadCrumbs = true
    ShowCodeCopyButtons = true
    ShowToc = true

    profileMode = true
    
    [params.profileMode]
        enabled = true
        title = "您的姓名"
        subtitle = "个人简历"
        imageUrl = "img/profile.jpg"
        imageTitle = "个人照片"
        
        [[params.profileMode.buttons]]
        name = "关于我"
        url = "about"
        
        [[params.profileMode.buttons]]
        name = "工作经验"
        url = "experience"
        
        [[params.profileMode.buttons]]
        name = "教育经历"
        url = "education"

    [[params.socialIcons]]
    name = "github"
    url = "https://github.com/your-username"

    [[params.socialIcons]]
    name = "email"
    url = "mailto:your.email@example.com"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "关于我"
    url = "/about/"
    weight = 10

  [[menu.main]]
    identifier = "experience"
    name = "工作经验"
    url = "/experience/"
    weight = 20

  [[menu.main]]
    identifier = "education"
    name = "教育经历"
    url = "/education/"
    weight = 30

[params.google]
    analytics = "UA-XXXXXXXXX-X"
