baseURL = 'https://tutukuaipao.github.io/dcx_resume/'
languageCode = 'zh-cn'
title = '个人简历'
theme = 'hugo-resume'

# 网站参数
[params]
  firstName = "张"
  lastName = "三"
  address = "深圳"
  phone = "188-xxxx-xxxx"
  email = "zhangsan@example.com"
  
  # 必要的显示设置
  showSkills = true
  showProjects = true
  showOpenSource = true
  showPublications = true
  showExperience = true
  showEducation = true
  
# 菜单配置
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4

# SEO 和其他设置
[markup]
  [markup.goldmark]
         [markup.goldmark.renderer]
           unsafe = true  # 如果你需要支持不安全的 HTML

[outputs]
  home = ["HTML", "JSON"]

# 语言设置
[languages]
  [languages.en]
    languageName = "English"
    weight = 1