baseURL = "http://example.org/"
title = "个人简历"
theme = "toha"
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

# 启用 Git Info
enableGitInfo = true

# 禁用默认的 taxonomies
disableKinds = ["taxonomy", "term"]

# 启用表情符号支持
enableEmoji = true

[languages]
  [languages.zh-cn]
    languageName = "中文"
    weight = 1

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = false
    noClasses = false
    style = "monokai"

[params]
    env = "production"
    description = "个人简历"
    author = "您的姓名"
    
    defaultTheme = "auto"
    ShowShareButtons = false
    ShowReadingTime = false
    displayFullLangName = true
    ShowPostNavLinks = true
    ShowBreadCrumbs = true
    ShowCodeCopyButtons = true
    ShowToc = true

    # GitHub 个人信息
    gitRepo = "your-username/your-repo"
    gitBranch = "master"

    # 背景图片
    background = "images/background.jpg"

    # 个人信息
    [params.author]
      name = "您的姓名"
      nickname = "昵称"
      image = "images/avatar.jpg"
      designation = "软件工程师"
      description = "热爱编程，热爱生活"
      resume = "files/resume.pdf"

    # 社交链接
    [[params.socialLinks]]
      name = "Email"
      icon = "fas fa-envelope"
      url = "mailto:your-email@example.com"

    [[params.socialLinks]]
      name = "Github"
      icon = "fab fa-github"
      url = "https://github.com/your-username"

    [[params.socialLinks]]
      name = "LinkedIn"
      icon = "fab fa-linkedin"
      url = "https://linkedin.com/in/your-username"

    # 导航栏自定义链接
    customMenus:
      - name: 博客
        url: "/posts"
      - name: 简历
        url: "/resume"

    # 主页设置
    [params.hero]
      enable = true
      intro = "你好! 我是"
      title = "您的姓名"
      subtitle = "软件工程师"
      content = "热爱编程，热爱生活"
      image = "images/avatar.jpg"

    # 关于部分设置
    [params.about]
      enable = true
      title = "关于我"
      image = "images/avatar.jpg"
      content = """
      我是一名软件工程师，热爱编程，热爱生活。
      """

    # 技能部分设置
    [params.skills]
      enable = true
      title = "技能"
      items:
        - title: "编程语言"
          skills:
            - name: "Go"
              percentage: 90
            - name: "Python"
              percentage: 85
            - name: "JavaScript"
              percentage: 80

    # 经验部分设置
    [params.experience]
      enable = true
      title = "工作经验"

    # 教育部分设置
    [params.education]
      enable = true
      title = "教育经历"

    # 项目部分设置
    [params.projects]
      enable = true
      title = "项目经验"

    # 成就部分设置
    [params.achievements]
      enable = true
      title = "成就与证书"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "关于我"
    url = "/about/"
    weight = 10

  [[menu.main]]
    identifier = "experience"
    name = "工作经验"
    url = "/experience/"
    weight = 20

  [[menu.main]]
    identifier = "education"
    name = "教育经历"
    url = "/education/"
    weight = 30

[params.google]
    analytics = "UA-XXXXXXXXX-X"
